### PR TITLE
Updates AlamoFire dependency to 1.3.0

### PR DESCRIPTION
**Pull request by colinta**
AlamoFire has added SSL Pinning, and a host of other features that I'm sure are just lovely, but that I don't have an immediate need for.

But I think SSL Pinning is the most compelling feature of this release.

### CODE REVIEW

**Comment by colinta** [comment]
```
> make ci
..............................................

	 Executed 46 tests, with 0 failures (0 unexpected) in 3.557 (3.574) seconds
```

**Comment by colinta** [comment]
Whaddup with those specs failing on CircleCI?  I haven't seen that on previous PRs.

**Comment by colinta** [comment]
Oh, I see, looks like it's a known issue since #161.

**Comment by rynbyjn** [comment]
Looks legit to me, would be sweet to get SSL Pinning in!

**Comment by ashfurrow** [comment]
OK cool, I'll merge and we can fix CI later. 

I don't think `master` is in a stable state to release a build, so you'll have to use this in your Podfile:

```ruby
pod 'Moya', :head
```

**Comment by colinta** [comment]
Do we need a minor version bump in Moya to use `:head` that way?

**Comment by ashfurrow** [comment]
I don't believe so, `:head` fetches from the repo's `HEAD` iirc.

**Comment by ashfurrow** [comment]
OK, so once #174 is done, I'll be release 2.0 in #149, so we should be :+1: soon.

**Pull request merged**
