### PR TITLE
sev 1 issue; pronunciation guide missing

### PR DESCRIPTION
**Pull request by lepinsk**

### CODE REVIEW

**Comment by orta** [comment]
Hah :dancers:

**Comment by orta** [comment]
why the close?

**Comment by lepinsk** [comment]
@ashfurrow is a tyrant. I'm gonna hard-fork the project io.js-style and rewrite it in [ArnoldC](https://github.com/lhartikk/ArnoldC).

**Comment by ashfurrow** [comment]
You absolute troll.

**Comment by ashfurrow** [comment]
❤️

**Comment by lepinsk** [comment]
:rage1: :

**Pull request closed without merging**
