### PR TITLE
Delete .gitmodules

### PR DESCRIPTION
**Pull request by jspahrsummers**
These submodules were already removed in abaf6cb0adafc0c0b482724edcf95f89225940d2, but the `.gitmodules` file was never modified to reflect that.

This was causing [Carthage update failures](https://github.com/Carthage/Carthage/issues/135#issuecomment-69566497) of the form:

```
Parse error: expected submodule commit SHA in ls-tree output: 
```

/cc @aschuch

### CODE REVIEW

**Comment by orta** [comment]
:+1:

**Comment by ashfurrow** [comment]
Thanks @jspahrsummers !

**Comment by jspahrsummers** [comment]
No problem. :tada:

**Comment by aschuch** [comment]
:+1:

**Comment by crmorse** [comment]
I am still getting this error with 0.6 and 0.6.1 in Carthage.  If I try going back to 0.5 (just to find anything that works) I get a different error:

> *** Checking out Moya at "0.5"
> fatal: reference is not a tree: 80cc05720013042eccfc8bc20a8304cd3ae656d7

I have tried an empty Cartfile with nothing but Moya and also fully deleting the Carthage/Checkout/Moya folder to start from scratch and I'm still getting this.  Is the errant `.gitmodules` in my own repo or in Moya's?

**Comment by ashfurrow** [comment]
Not sure. Any suggestion, @jspahrsummers?

**Comment by jspahrsummers** [comment]
@crmorse If you're using Carthage to manage submodules, you might be hitting https://github.com/Carthage/Carthage/issues/320.

**Pull request merged**
