### PR TITLE
Swift 1.2 upgrade

### LINKED ISSUE #113: Update to Support Latest Swift & Dependencies
Now it's strictly binded to Alamofire version `1.1.0` 
https://github.com/ashfurrow/Moya/blob/master/Moya.podspec#L23

But it's `1.2.1` version already released. Is there any reasons to stay with `1.1.0`?

### PR DESCRIPTION
**Pull request by skywinder**
Hi, @ashfurrow! I update your demo project and fix several issues. At least - now Demo project is working! There some errors with the tests, but I will try to fix them later. But you awesome project is works! :wink: 
Fixes #113.

### CODE REVIEW

**Comment by skywinder** [comment]
Related with #113.

**Comment by ashfurrow** [comment]
Sounds good to me – CI is gonna break since Travis is sucky. Can you update the README status, too?

**Comment by orta** [comment]
https://github.com/Quick/Quick/pull/289

**Comment by ashfurrow** [comment]
Thought they were still in invite-only beta?

**Comment by skywinder** [comment]
Sorry, I'm not familiar with circle-ci. 
It seems that you can sign up there with your github account w/o invite.

**Comment by skywinder** [comment]
@ashfurrow bdw, as you can see - I create PR to branch  `swift-1.2`, not to `master`, so this merge will not break build status for your repo!

**Comment by orta** [comment]
yeah, thats incidental to this PR :+1:

**Comment by ashfurrow** [comment]
Cooool.

**Comment by ashfurrow** [comment]
Thanks for the PR!

**Pull request merged**
